### ISSUE TITLE
Set `SameSite` attribute on API token cookie when deleting it

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#15165]
Django 2.2.15 added the ability to set `samesite` when deleting a cookie - See https://code.djangoproject.com/ticket/31790

We should also do that when deleting our API token cookie.

**Comment by diox** [comment]
Django commit: https://github.com/django/django/commit/f1a6e6c817f3205ea7da6f973f51524ff630dda5

We just merged Django 2.2.15 upgrade in https://github.com/mozilla/addons-server/commit/596a9c76a778664418e2aaaff5ac956c5f117a37

**Comment by AlexandraMoga** [comment]
@diox is there anything I could verify for this issue?

**Comment by diox** [comment]
On logging out, you should ensure that both the `sessionid` and `frontend_auth_token` are correctly cleared.

**Comment by AlexandraMoga** [comment]
@diox I've tested the logout process across the site on stage and I have the following results:

- frontend, revtools and code-manager:
  - both the `sessionid` and the `frontend_auth_token` cookies are cleared completely  
- developer hub
  - there is an initial `sessionid` cookie when you first access the page; the cookie changes its value when you log in; at logout, the cookie is still present but its value is changed again, i.e. it won't keep the value from the logged in session
  - the `frontend_auth_token` cookie is cleared completely
- admin tools
  - neither the `sessionid` or the `frontend_auth_token` are cleared because logging out from admin tools doesn't work - see #13200

**Comment by diox** [comment]
Ok, that's fine.
