### ISSUE TITLE
Return HTTP 409 Conflict error in add-on API when submitting a duplicate version

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#20387]
In the new add-on API, submitting a version that already exists returns a 400 error with `Version {version_string} was uploaded before and deleted.` or `Version {version_string} already exists.`.

It should return a 409 instead to make it easier for clients to programmatically differentiate between a duplicate submission and more general bad request errors.

**Comment by diox** [comment]
Note: I also implemented that same behavior for entirely new add-ons. So trying to submit a new add-on or new version that already exists (same guid for add-on creation, same version number for version creation) should result in a 409.

**Comment by ioanarusiczki** [comment]
@diox 

- I tried on -dev with new versions for both  POST and PUT methods and I get the 409

![409](https://user-images.githubusercontent.com/33448286/221210004-e93fb4fc-4b7f-4a1d-81c8-c2aa84dffe8d.png)

- When I try with a guid that already exists at add-on creation I  still get a 400.

**Comment by diox** [comment]
> When I try with a guid that already exists at add-on creation I still get a 400.

Could you give more details about the request you made ? What HTTP verb was used, what url did you use and what exact error message you got ?

**Comment by ioanarusiczki** [comment]
@diox Sorry, I re-checked the scenario and I get a 409 Conflict with "Duplicate add-on ID found" 

I used an editor on manifest.json to add the guid so my assumption is that I did something wrong in the .json file.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDSRV-269
