### ISSUE TITLE
Theme review buttons are not aligned correctly in editor tools

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2067]
**Steps to reproduce:**
1. Open review detail page for a theme: i.e: https://addons.allizom.org/en-US/editors/themes/queue/single/testtheme0991125123

**Expected results:**
There are no layout or display issues.

**Actual results:**
The review buttons are not aligned correctly. All the buttons should be displayed in one line.

**Notes/Issues:**
Verified in FF45(Win7) Issue can be reproduced in -dev and stage.
Screencast for this issue: http://screencast.com/t/q4eJBjU3Qx

**Comment by ValentinaPC** [comment]
I cannot approve a theme because of this "button-issue", I think.
Please see the screencast: http://screencast.com/t/m1wkoEVLoP

**Comment by madalincm** [comment]
Approving themes is working but the buttons layout is still not correct.
Please view this screenshot:
![themereviewlayout](https://cloud.githubusercontent.com/assets/15685441/14241028/de985398-fa51-11e5-9fea-abf015d2d1f2.png)

**Comment by tofumatt** [comment]
I can't replicate this on my local dev server:
<img width="1011" alt="screenshot 2016-04-04 23 30 51" src="https://cloud.githubusercontent.com/assets/90871/14266056/7571f92a-fabd-11e5-9e5e-11400bc17ee5.png">

@madalincm: which site are you encountering this error on? It should be fixed on -dev, but it might not have made it to staging yet.

**Comment by madalincm** [comment]
I've tested on addons-dev.allizom.org  on FF45(Win7). The issue is still reproducing for me and the rest of the qa team. 
I've tried again with a clean profile and i had the same result.
Please view this screenshot:
![themereview02](https://cloud.githubusercontent.com/assets/15685441/14310986/b0cd11f4-fbed-11e5-8760-dc26ee9762d1.png)

**Comment by muffinresearch** [comment]
It's like a font-size descrepency with the web-font vs the local one.

**Comment by muffinresearch** [comment]
I can only repro on windows. However it's fixed on -dev since the button font-size was reduced already.

![screenshot_15_04_2016__11_11](https://cloud.githubusercontent.com/assets/1514/14558526/e4080ed4-02fa-11e6-822c-bf4b0e8f8f84.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-04-15_1501](https://cloud.githubusercontent.com/assets/15685960/14560864/197abd76-031b-11e6-8f00-49b5feed1c75.png)
