### ISSUE TITLE
Merged Upload Versions and Vanishing XPI content & data

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-server#2240]
I checked the following addon which contained 2 binary files: eclipse.exe & eclipsec.exe (Version 1.1.1 · April 4, 2016)
`https://addons.mozilla.org/en-US/editors/review/feedly-synchronizer`

Just now I noticed that the Info Request flag was gone.
Looking at the addon details, I noticed the following:
 	

> By Antonio Miras on Apr 4, 2016 9:17:09 PM
> 
> More information requested 	
> By erosman on Apr 5, 2016 6:19:16 PM
> 
> re: eclipse.exe & eclipsec.exe
> 
> This version contains binary, obfuscated or minified code. In order to pass review, please provide the original sources and instructions on how to generate the final XPI.
> 
> You can upload the sources using the AMO Developer Hub, by selecting your latest version of your add-on and looking for the source code upload field. You can also do this when submitting new versions, which will reduce your review waiting time. If you can't provide your sources or build instructions this way, you can include the information in the Notes to Reviewers. In the case of obfuscated or machine-generated JavaScript, including cross-compiled code and preprocessed template code, instructions must be provided to generate the same code in the resulting XPI.
> 
> If sources have not been provided within 7 days, this version will be rejected and removed from our queues.
> 
> You can find our policies regarding source code submission and handling here: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#Binary_Components_Obfuscated_Code
> 
> 	
> By Antonio Miras on Apr 6, 2016 10:12:16 AM
> 	
> By Antonio Miras on Apr 6, 2016 10:12:16 AM
> 	
> By Antonio Miras on Apr 6, 2016 10:12:16 AM

Inspecting the addon, I noticed it no longer had the mentioned binary files (eclipse.exe & eclipsec.exe)

Unless users are able to edit the XPI contents on AMO (unlikely), it appears that a new version was uploaded and got merged with the previous data/upload.
What did happen to the previous Version 1.1.1 · April 4, 2016?

In any case, it appears to be a bug.

Reference:
It appears to relate to the following previously logged bug:
[ Changing the file ID on web-based actions is causing numerous complications](https://github.com/mozilla/addons-server/issues/1419)

It could also relate to:
[Review is submitted for latest version even if previous version was being reviewed](https://github.com/mozilla/addons-server/issues/1542)

**Comment by AMArostegui** [comment]
Hello.

Yes, I did just that. As no new features were added or bugs fixed, I decided to keep the version number (1.1.1, the same I uploaded on Apr 4) and just update the XPI package (Apr 6).

I removed the original file and uploaded the new one without the binary files; so the first one (same number 1.1.1) is no longer there, because I deleted it.

**Comment by erosman** [comment]
> Yes, I did just that. As no new features were added or bugs fixed, I decided to keep the version number (1.1.1, the same I uploaded on Apr 4) and just update the XPI package (Apr 6).
> 
> I removed the original file and uploaded the new one without the binary files; so the first one (same number 1.1.1) is no longer there, because I deleted it.

The issue is not what you did. :)

The issue is that the AMO should have kept a reference to the previous upload (even when you deleted it) AND NOT merged the review data of the previous upload to the new upload (even with the same number).

Just for your Info ...
Reusing the same version number, will cause complication for the addon users anyway. New uploads must have a higher version number than the previously uploaded versions otherwise those files do not propagate across our mirror network correctly, and many users will receive the old version, which they will be unable to install due to checksum mismatches.

**Comment by AMArostegui** [comment]
Ok, so I think I'd better create version 1.1.2. Right?

Should I remove 1.1.1 or you want me to keep it to track this bug?

**Comment by erosman** [comment]
> Ok, so I think I'd better create version 1.1.2. Right?
You would be better off uploading a new version. You can leave 1.1.1 as it is.

**Comment by jvillalobos** [comment]
It shouldn't be possible to re-upload with the same version number. I suppose the developer uploaded a new file to the existing version, which I believe is an edge case that isn't completely covered. It looks like this particular issue has been solved by uploading a new version. We have some longer term plans to remove this file upload problem, so I'm closing this bug.

**Comment by erosman** [comment]
The bug still exist.

Developer uploaded v1.1.1
I reviewed v1.1.1 and left a Info Request since it contained binary files
Developer deleted v1.1.1
Developer uploaded a new file but with the same version number v1.1.1

The review for the previous file (the first v1.1.1) was merged into the new file.
Even when a XPI is deleted, it's history should remain along with the review notes which is not the case and hence the **bug**.

**Comment by jvillalobos** [comment]
@wagnerand knows where we are with version resubmission better than I, so I'll let him figure out what happened here. As far as I know, deleting and reuploading shouldn't work.

**Comment by wagnerand** [comment]
If file has not been reviewed yet, a developer can delete the file *inside* the pending version and upload another one. @jvillalobos do we want to change that?

**Comment by jvillalobos** [comment]
It's not a priority at the moment, IMO, but I wanted to confirm that it was what indeed happened in this case and not something else.

**Comment by erosman** [comment]
> If file has not been reviewed yet, a developer can delete the file inside the pending version and upload another one. @jvillalobos do we want to change that?

That is obviously NOT the case. The developer deleted the file AFTER receiving the Info request (and realising the packing error).
Unless you mean if the file is not passed/rejected.

In any case, that would create confusion for everyone, like in this case where there is an Info Request attached to the version while it actually doesn't belong to that particular XPI and it belongs to a different XPI which is no longer available and **hence the bug that the data belonging to a previous XPI was merged into a new XPI.**

**Comment by erosman** [comment]
Could this be another example of the bug?
`https://addons.mozilla.org/en-US/editors/review/no-need-flash-plugin-on-embede`


> Version 1 · January 1, 2016
> Preliminarily approved By Leszek Życzkowski on Jan 22, 2016 12:58:15 PM
> Rejected By Leszek Życzkowski on Jan 26, 2016 5:46:20 AM
> By Mozilla on Mar 5, 2016 12:01:41 AM
> Approved By Leszek Życzkowski on Mar 8, 2016 9:04:54 PM
> By Mozilla on Mar 29, 2016 3:27:56 PM <-- What is this
> By Vasiliy Temnikov on Apr 2, 2016 6:37:07 PM
> By Vasiliy Temnikov on Apr 2, 2016 6:37:07 PM
> By Vasiliy Temnikov on Apr 2, 2016 6:37:07 PM
> By Vasiliy Temnikov on Apr 2, 2016 6:37:07 PM

**Comment by wagnerand** [comment]
>  By Mozilla on Mar 29, 2016 3:27:56 PM <-- What is this

This is the bulk validation tool checking for compatibility issues and bumping the maxversion.

**Comment by eviljeff** [comment]
> PS. @eviljeff Does this issue relate to Deleting reviewed file causes huge extra effort in reviewing ??

It's connected but I didn't try to fix it at the time.
