### ISSUE TITLE
HTML small issue for EULA section from "Manage Authors & License" in French

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2344]
Steps to reproduce:
1. Sign in to AMO-stage page https://addons.allizom.org/
2. Change the language to French https://addons-dev.allizom.org/fr/
3. Submit an add-on and add an EULA
4. Observe the EULA field title

Expected results:
There are no display or layout issues.

Actual results:
There is a HTML character listed. (&nbsp;)

Notes/Issues:
The issue can also be seen in "Manage Authors & License", eula section.
Verified on FF45(Win 7). Reproducing on AMO-stage, dev and prod.
Please see screenshots: 
![2016-04-13_1444](https://cloud.githubusercontent.com/assets/15685960/14492636/6402a1bc-0189-11e6-9537-ad519012c829.png)
![2016-04-13_1506](https://cloud.githubusercontent.com/assets/15685960/14492641/69727802-0189-11e6-9483-585a85d6308a.png)

**Comment by andymckay** [comment]
Assuming I'm looking at the same part, its fixed with a new translation now:

<img width="825" alt="screenshot 2017-01-16 15 01 37" src="https://cloud.githubusercontent.com/assets/74699/22001905/bf89befa-dbfc-11e6-993c-3a7fb3ad7d85.png">

**Comment by ValentinaPC** [comment]
Yeah, sort of in the same part -because with the new submission flow, the EULA was removed and can be added only from "Edit information"-"Manage Authors & License" page from Dev Hub (as I also mentioned above).
The minor issue is still there:
![there](https://cloud.githubusercontent.com/assets/15685960/22011862/dcf35134-dc99-11e6-919a-b0f11d8883ec.png)

**Comment by EnTeQuAk** [comment]
![screenshot from 2018-01-30 14-36-13](https://user-images.githubusercontent.com/139033/35568950-f0a4147e-05ca-11e8-883b-a900399dd7c3.png)

Just wait long enough and things fix themselves magically.

**Comment by vcarciu** [comment]
Verfied as fixed : 
![eulafr](https://user-images.githubusercontent.com/1583842/35570296-77347536-05d7-11e8-9de2-2ec76e7d325f.png)
