### ISSUE TITLE
Hidden add-ons should not be displayed in search results pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2377]
Please see the https://bugzilla.mozilla.org/show_bug.cgi?id=1162559 or follow the next STR:

1. Sign in to AMO-stage page https://addons.allizom.org/en-US/firefox/
2. Disable an add-on (go to Edit listing page-> Manage status & versions -> hidden)
3. Sign out and search the add-on
4. Observe the search suggestions and search results

Expected results:
The hidden add-on is not listed anywhere.

Actual results:
The hidden add-ons are listed through search suggestions and in search results page.

Notes/Issues:
Verified on FF45(Win 7). Issue is reproducing on AMO-stage and dev.
Screenshots for this issue: 
![2016-04-14_1725](https://cloud.githubusercontent.com/assets/15685960/14531434/fc3d7362-0265-11e6-8514-5d08c07c6480.png)

**Comment by ValentinaPC** [comment]
Hidden add-on can also be added in the "Require an add-on..." section.
Verified on AMO-stage FF45(Win 7). 
Please see : 
![require](https://cloud.githubusercontent.com/assets/15685960/14670466/f7209618-06f5-11e6-8774-ff6c9f7cce5f.gif)

**Comment by andymckay-limited-access** [comment]
@diox is this related to current elastic search changes or has this always been the case?

**Comment by diox** [comment]
AFAIK it has always been the case, and only search suggestions are affected. It should be simple enough to fix - the search suggestions view just needs to call the right method to filter out hidden add-ons.

**Comment by diox** [comment]
@ValentinaPC , I can't reproduce the first part: search suggestions never show disabled add-ons for me. I've been looking at the code and it's filtering correctly everywhere as far as I can tell.

The add-on requirement thing is valid and should be fixed, though.

**Comment by ValentinaPC** [comment]
@diox : :smile: Well, sorry about the "AMO wording". I was talking from the start, only, about HIDDEN add-ons, as I wrote at step 2, but making an add-on hidden, turns the add-ons status into "disabled".
Sorry again about the confusion.

**Comment by diox** [comment]
@jvillalobos @wagnerand see https://github.com/mozilla/addons-server/issues/2377#issuecomment-216222414 any idea what we should do ?

**Comment by jvillalobos** [comment]
An add-on that is disabled by the developer has inactive = 1, rather than status = disabled. However, for both of those cases, we shouldn't display the add-on anywhere, including both cases mentioned in this issue. I think it's okay to hide add-ons even if they are dependencies. I doesn't help users to show a dependency they can't install, and it's a bit of an edge case anyway.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev using FF46(Win 7).
Issue is still reproduced.
Add-ons are still displayed in search results page and between search suggestions.
Please see he screenshots:
![2016-05-09_1456](https://cloud.githubusercontent.com/assets/15685960/15112392/96402902-15f6-11e6-85bd-5d0a897bbd40.png)
![2016-05-09_1457](https://cloud.githubusercontent.com/assets/15685960/15112395/9b4c4e94-15f6-11e6-8b78-c4a22fcb1249.png)

**Comment by diox** [comment]
@ValentinaPC can you check that this wasn't just a cache issue ?

**Comment by ValentinaPC** [comment]
@diox : I've tried with an old disabled add-on, and seems to work as expected.
Postfix screenshots:
![editlisting](https://cloud.githubusercontent.com/assets/15685960/15221141/e766e2e8-1872-11e6-965c-2de81386ba94.png)
![search](https://cloud.githubusercontent.com/assets/15685960/15221145/eb43c084-1872-11e6-8400-90ecfd76d0cb.png)

But for a fresh disabled add-on the issue is still reproducing. Maybe is because in AMO-dev the updates apply slower?

**Comment by ValentinaPC** [comment]
Verified as fixed
