### ISSUE TITLE
Wrong error message while uploading an add-on after changing the language

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#5190]
Steps to reproduce:
1. Go to add-on submission page and select an invalid file for submission (tried with a legacy add-on with `maxVersion` 55) https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed (but do not click "Continue")
2. Change the language (i.e. https://addons-dev.allizom.org/ga-IE/developers/addon/submit/upload-listed)
3. Select the same file again

Expected results:
A specific error message is returned.

Actual results:
File fails validation with next error: "Sorry, we couldn't load your add-on."

Notes/Issues:
- not reproducible every time;
- tried with webextensions - did not reproduced
- tried with unrestricted add-ons - did not reproduced
- maybe has something to do with "locale" folder?

Verified on FF55(Win 7) on dev and stage.
Screenshot for this issue: 
![2017-04-18_1541](https://cloud.githubusercontent.com/assets/15685960/25131322/f0bdba00-244d-11e7-8602-7c1f200a8b52.png)
![ja](https://cloud.githubusercontent.com/assets/15685960/25131611/08208e38-244f-11e7-8660-54ff6123b7ab.png)

Attaching one of the used add-ons.
[an55-sc.zip](https://github.com/mozilla/addons-server/files/929614/an55-sc.zip)

I'll also add the `legacy` label, but not sure if totally related.

**Comment by EnTeQuAk** [comment]
I fixed this by making the error message translatable but now that I think about it… is that what you actually mean in this error or what do you mean by "specific error message"? Like, after switching the language (and explicitly selecting the file again!) you don't get any validation errors like you did before?

**Comment by ValentinaPC** [comment]
> I fixed this by making the error message translatable but now that I think about it… is that what you actually mean in this error or what do you mean by "specific error message"? Like, after switching the language (and explicitly selecting the file again!) you don't get any validation errors like you did before?

When I said I don't get any specific validation error I meant that in stead of "Starting with Firefox 53, new extensions on this site can only be WebExtensions" - named above "specific error" translated in the selected language I receive just a "Sorry, we couldn't load your add-on." error message.

And the issue, as described in the first comment is still reproducing, but as I said before, not every time.
Please see video:
![specific](https://cloud.githubusercontent.com/assets/15685960/25532874/75c1e9c4-2c37-11e7-9174-36e8e8d8936c.gif)

**Comment by EnTeQuAk** [comment]
Ah, I misunderstood the issue then. I'm on PTO now so I can't look into that any further but maybe once I'm back or someone else can depending on importance, looks like a edge-case to me though.

**Comment by diox** [comment]
(not related to legacy switch off - would happen regardless, removing label)
