### ISSUE TITLE
Add specific admin flag for Static themes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#7855]
Follow up for #7765 

After testing Static themes review page I've had some observations:

1. themes can be composed of several backgrounds, so an image gallery could actually be useful for reviewers; in the current implementation, you can't know how many images are there unless you navigate through all the available screenshots
2. 'Request super review' will set a 'Needs Admin Code Review' flag which makes more sense for extensions; maybe a new flag that will distinguish static themes from the rest of the add-ons could be put in place?

----------------------------------------------------------------------------------------
Comments from @eviljeff 
>themes can be composed of several backgrounds, so an image gallery could actually be useful for reviewers; in the current implementation, you can't know how many images are there unless you navigate through all the available screenshots

The caption on the preview shows x of y, but anyway, I believe this satisfies "possible to inspect the background image(s) individually". Jorge to file follow-ups if the implementation needs changing as there weren't any UX descriptions or mock-ups.

>'Request super review' will set a 'Needs Admin Code Review' flag which makes more sense for extensions; maybe a new flag that will distinguish static themes from the rest of the add-ons could be put in place?

It's a bit of an open question what admin flagging should look like for static themes. (I couldn't see any reference to it in the PRD/issues so just left it at standard add-on admin flag). It probably shouldn't be "Needs Admin Code Review" but it's not clear what it should be yet. I'll leave it to Jorge to specify.

cc @jvillalobos to hear your opinion regarding the above observations

**Comment by jvillalobos** [comment]
> What type of "Admin Review" is it - "code review", "content review", or a new type of admin review just for themes?

Probably best to have a new type of admin review, to avoid conflicts with existing admin reviews.

**Comment by eviljeff** [comment]
refocusing the issue to admin flags - the other problems are addressed in other issues.

**Comment by vcarciu** [comment]
@eviljeff : if the reviewer is in Reviewers:Themes group then after requesting a super review I correctly see the flag : 
![adminstaticthemerev](https://user-images.githubusercontent.com/1583842/38628574-59706bc0-3dba-11e8-8407-f1583185b5c4.png)

If I request a super review using an admin account for a static theme , I still see "Needs Admin Code Review" flag. Is this correct?

Thanks

**Comment by vcarciu** [comment]
I am sorry for my last comment, I selected an item from "Static theme" queue, but it was an extension, not a static theme, so the flag is correct.

Marking bug as verified.
